import type { ThemeConfig } from "antd";

export const appTheme: ThemeConfig = {
  token: {
    colorPrimary: "var(--color-brand-primary)",
    colorPrimaryHover: "var(--color-brand-primary-hover)",
    colorPrimaryActive: "var(--color-brand-primary-active)",
    colorSuccess: "var(--color-status-success-fg)",
    colorInfo: "var(--color-status-info-fg)",
    colorWarning: "var(--color-status-warning-fg)",
    colorError: "var(--color-status-danger-fg)",
    colorText: "var(--color-text-default)",
    colorTextSecondary: "var(--color-text-muted)",
    colorTextTertiary: "var(--color-text-muted)",
    colorBgBase: "var(--color-bg-canvas)",
    colorBgLayout: "var(--color-bg-canvas)",
    colorBgContainer: "var(--color-bg-surface)",
    colorBgElevated: "var(--color-bg-surface)",
    colorBorder: "var(--color-border-default)",
    fontFamily: "var(--font-family-base)",
    fontSize: 16,
    fontSizeSM: 14,
    fontSizeLG: 18,
    lineHeight: 1.5,
    lineHeightSM: 1.4,
    lineHeightLG: 1.6,
    borderRadius: 8,
    borderRadiusSM: 4,
    borderRadiusLG: 12,
    borderRadiusXS: 2,
    borderRadiusOuter: 8,
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 48,
    controlHeightXS: 24,
    boxShadow: "var(--shadow-md)",
    boxShadowSecondary: "var(--shadow-sm)",
    boxShadowTertiary: "var(--shadow-sm)",
  },
  components: {
    Button: {
      fontWeight: 600,
      iconGap: 8,
      defaultShadow: "var(--shadow-sm)",
      primaryShadow: "var(--shadow-md)",
      dangerShadow: "var(--shadow-sm)",
    },
  },
};
